Workflow:
  '@WorkflowId': '{779b48b5-36bb-f011-bbd3-6045bda07122}'
  '@Name': Change_room Old
  JsonFileName: /modernflows/779b48b5-36bb-f011-bbd3-6045bda07122/Change_roomOld-779B48B5-36BB-F011-BBD3-6045BDA07122.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Change_room Old
